### ISSUE TITLE
error

### ISSUE THREAD

**Issue by murilolivorato** [hifarer/Vueditor#12]
Heelo my friend , nice code .
It is giving me an error . can you have a look .

Thanks

![eeror1](https://cloud.githubusercontent.com/assets/19832238/23873132/baab21a0-080f-11e7-8b02-eb22faf44148.jpg)

**Comment by hifarer** [comment]
hi there, the ui in your picture does looks like Vueditor, maybe you should open an issue  here https://github.com/PeakTai/vue-html5-editor
