### ISSUE TITLE
How to contribute to the dev branch?

### ISSUE THREAD

**Issue by ibudisteanu** [hifarer/vueditor#16]
hi hifarer!

The vueditor project is really awesome. I would really like to contribute to your development branch like introducing a media embedded link for youtube, mentions (@ for mentioning people and : for emojis).

But, the thing is that I have tried to download the development branch https://github.com/hifarer/vueditor/tree/develop  but I can not make it work/test the any changes I am doing.

I did the following:

`downloaded the development branch`
`npm install` // it installs the required node_modules for the project, no error
`npm build` //the console doesn't output any message and I suspect it is not doing anything.

Also, when are you planning releasing the new version that includes the markdown and it is in development?

Thanks

**Comment by hifarer** [comment]
hi, glad to know you like it, try `npm run build`, you can see it in the package.json `scripts`. The dev branch is unstable.
