### ISSUE TITLE
TypeError: e._h is not a function

### ISSUE THREAD

**Issue by vanessa-joyce** [hifarer/Vueditor#2]
Just tried to install your awesome editor but got the mentioned error.
Some people using a different component had the same issue which occured due to Vue 2.1.5 where _h is replaced with _c (https://github.com/ElemeFE/element/issues/1725).

I would very appreciate it if you could provide some solution for your component. 

Thank you

**Comment by hifarer** [comment]
Hi there, I rebuild this project using latest version of the dependencies, it should work now, thank you for feed back.

**Comment by vanessa-joyce** [comment]
That was fast, thank you! I just gave it a try and it works like a charm.
