### ISSUE TITLE
设置中文语言时遇到的问题

### ISSUE THREAD

**Issue by caiyawen** [hifarer/vueditor#27]
`The dist/language folder has an full example inside. Adding a script tag or use import, require to
bring the language object in, then make it an attribute of the config for initialize`
文档中的说法是langage.cn.js可以直接import或require是么，可是没有export我怎么引用呢？
现在我的做法是直接把文件里的对象拷贝出来，但是我觉得这样好像不大好。想要改进一下，望指点，谢谢～

**Comment by hifarer** [comment]
你可以直接修改 dist/language/lang.cn.js 给它加上export 之内的，也可以用webpack自动化处理，或者用script标签直接引入。我把它独立出来就是为了解耦，怎么用都行。
