### ISSUE TITLE
好多问题。。。

### ISSUE THREAD

**Issue by Meowu** [hifarer/vueditor#30]
上床图片的时候，popup，点击取消按钮会刷新整个页面，点击确定上传成功后也会刷新整个页面。
复制excel内容过来会生成table，但是没有边框，只有一个个内容，看起来不像一个表格。

**Comment by hifarer** [comment]
你好，未发现会刷新整个页面的情况。
复制excel粘贴的结果是浏览器控制的，编辑器没有作任何处理，目前已加入无格式粘贴选项。
