### ISSUE TITLE
语言设置是这样吗? 好像无效啊

### ISSUE THREAD

**Issue by alexxuan** [hifarer/vueditor#38]
按照文档说的做了无效
import 'vueditor/dist/language/lang.cn.js'

**Comment by alexxuan** [comment]
import 'vueditor/dist/language/lang.cn.js'
// your config here
let config = {
lang:lang,
  toolbar: [
     'removeFormat', 'undo', 'redo', '|', 'code', 'element', 'fontName', 'fontSize', 'foreColor', 'backColor', 'divider', 'bold', 'italic', 'underline', 'strikeThrough',
        'link', 'unLink', 'divider', 'subscript', 'superscript', 'divider', 'justifyLeft', 'justifyCenter', 'justifyRight', 'justifyFull',
        '|', 'indent', 'outdent', 'insertOrderedList', 'insertUnorderedList', '|', 'emoji', 'picture', 'table', '|', 'sourceCode', 'markdown'
  ],
  fontName: [
    {val: 'arial black'}, 
    {val: 'times new roman'}, 
    {val: 'Courier New'}
  ], 
  fontSize: ['12px', '14px', '16px', '18px', '0.8rem', '1.0rem', '1.2rem', '1.5rem', '2.0rem'],
  uploadUrl: '',
};
Vue.use(Vueditor, config);
Vue.component(VTable.name, VTable)
Vue.component(VPagination.name, VPagination)
Vue.use(ElementUI)
Vue.use(BaiduMap, {
  ak: 'Ks378kBpXlxhAmwBxGz6DktiCld0Khcz'
})

**Comment by hifarer** [comment]
你好，如果用import 可以这样
`import lang from 'exports?lang!vueditor/dist/language/lang.cn.js'`
或者直接script引入。
另外issue一般是用来提bug或者新功能需求的，不是用来问问题的，有问题可以通过邮件和我直接联系。hifarer@qq.com
