### ISSUE TITLE
I did a fork

### ISSUE THREAD

**Issue by chiaweilee** [hifarer/vueditor#42]
Thank for your codes.

I did a fork version and do some changes, I think them works..

I added props to load default content and emit event to get new content changed.

See https://github.com/chiaweilee/vueditor

**Comment by etewiah** [comment]
Hi @chiaweilee I found your fork very helpful - thanks for sharing it.

Why don't you create a pull request with it?

**Comment by chiaweilee** [comment]
I'm so glad you like it.
I did a fork for a project that time, so I made some changes which fit to my project..
So I need refactor my code if I pull a request with it.

I will do it later anyway.

Thank you.
