### ISSUE TITLE
Webpack构建出现重复的Vue依赖

### ISSUE THREAD

**Issue by yscoder** [hifarer/vueditor#6]
![image](https://cloud.githubusercontent.com/assets/12295378/22051983/0fd5e5d8-dd82-11e6-8820-8776b24677d0.png)

如图，Vueditor 的 Vue 依赖在 `dependencies` 中，打包时由于和项目中 Vue 版本不一致出现了打包了两个 Vue 的情况。

可以参考其他 Vue 组件库的 package.json，把 Vue 和 Vuex 依赖放在 `devDependencies` 或 `peerDependencies` 中。

**Comment by hifarer** [comment]
谢谢反馈，会尽快解决。

**Comment by hifarer** [comment]
目前已经降低了版本依赖，Vue.js 2.0.5以上，Vuex 2.0.0以上即可。
