### ISSUE TITLE
无法设置上传图片时的验证header

### ISSUE THREAD

**Issue by dengqianyi** [hifarer/vueditor#9]
如题，我上传图片的接口需要经过basic auth验证。
看了代码
let formData = new FormData(form);
let xhr = new XMLHttpRequest();
xhr.open('POST', fileuploadUrl);
xhr.send(formData);

没有机会进行setHeader
我这边怎么改？

**Comment by xiaoqing-tan** [comment]
楼主解决了吗，我也遇到了这个问题，莫非只有修改源码？

**Comment by hifarer** [comment]
现已支持自定义图片上传程序，请看最新文档。
